{% set name = "colomoto_jupyter" %}
{% set version = "9999" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../

channels:
  - colomoto

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - beautifulsoup4
    - boolean.py
    - networkx >=2.0
    - pydot >=1.2.3
    - pygraphviz
    - pandas

about:
  home: https://github.com/colomoto/colomoto-jupyter
  summary: 'CoLoMoTo helper functions for Juypter integration'
  license_family: LGPL
  license: LGPL v3+/CeCILL-C

