{% set name = "colomoto_jupyter" %}
{% set version = "9999" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python
    - pip

  run:
    - espresso-logic-minimizer
    - python
    - beautifulsoup4
    - boolean.py
    - networkx >=2.0
    - pydot >=1.2.3
    - pygraphviz
    - pandas

test:
    imports:
        - colomoto.minibn
        - colomoto
        - colomoto_jupyter

about:
  home: https://github.com/colomoto/colomoto-jupyter
  summary: 'CoLoMoTo helper functions for Juypter integration'
  license_family: LGPL
  license: LGPL v3+/CeCILL-C

