name: Publish conda package

on:
  push:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: test
      run: |
        conda install -y anaconda-client conda-build
        conda build conda
    - name: Conda publish
      uses: docker://colomoto/conda-builder:latest
      with:
        subdir: conda
        anaconda_user: colomoto
        anaconda_token: ${{ secrets.ANACONDA_TOKEN }}
